### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by Mylszd** [Jiaoma/SHGD#1]
您好，PANDA数据集中分成很多部分，请问应该下载PANDA中的哪些数据集放到工程目录中?谢谢。

**Comment by Jiaoma** [comment]
PANDA数据集在申请下载后分别得到video_test, video_train, PANDA_IMAGE, video_annos.zip。本项目仅使用video_test, video_train和video_annos.zip。其余具体是哪些video，哪些anno被用到参见dataset.py中的数组，具体train/test划分follow PANDA的文章设定。下载得到的目录结构已经是readme提到的结构了。我的描述是否已解决你的问题？ @Mylszd

**Comment by Mylszd** [comment]
好的，谢谢您！

**Comment by BennyLia** [comment]
@Jiaoma 您好，我有相同的问题，目前PANDA网站没有相应的video数据了，您能分享一下百度网盘的链接吗，谢谢！不方便发这里的话麻烦发一下邮箱 2669308610@qq.com，谢谢。

**Comment by Mylszd** [comment]
@Jiaoma 我也网上找了好久没有找到相关的原始数据集，能发一下吗？

**Comment by Mylszd** [comment]
@BennyLia 可以发邮件给官方 可以获取数据集
