### ISSUE TITLE
extractor.py运行问题

### ISSUE THREAD

**Issue by Mylszd** [Jiaoma/SHGD#2]
您好，能不能提供一下更改之后的UniPose代码，在运行extractor.py的时候，没有features=model.test(image,0,vis,key[1],key[2])相应的代码，谢谢。

**Comment by Mylszd** [comment]
目前运行调试由于UniPose工程的差异较多，很难获取extractor.py的生成的关键点信息，有时间麻烦更新一下code。

**Comment by Jiaoma** [comment]
Fixed in https://github.com/Jiaoma/SHGD/commit/1bcc443b1c8996d0495dcb8c85af85d2aa1798b2
