### ISSUE TITLE
No evaluation module for JRDB dataset

### ISSUE THREAD

**Issue by fangzl123** [Jiaoma/SHGD#3]
Hi, I have noticed that you've mentioned the method reached SOTA for the JRDB-Act dataset in the paper, but I didn't find any evaluation modules in the codes for this test, and there's only a PANDA-dataset module. Would you mind providing this testing part? Or are there any other methods to obtain the Precision and Recall numbers in the paper?

**Comment by Jiaoma** [comment]
Fixed in https://github.com/Jiaoma/SHGD/commit/1bcc443b1c8996d0495dcb8c85af85d2aa1798b2. The training and testing on the JRDB dataset follow the same way as PANDA.
