### ISSUE TITLE
特征提取问题

### ISSUE THREAD

**Issue by Mylszd** [Jiaoma/SHGD#4]
您好，更新之后还存在一点问题：
在SHGD/feature_extract/extractor.py的111行，使用的SHGD/feature_extract/unipose.py中缺少对应的test函数

发生异常: TypeError
test() takes 2 positional arguments but 6 were given
  File "SHGD/feature_extract/extractor.py", line 111, in extract_PANDA_skeleton_features
    features=model.test(image,0,vis,key[1],key[2]) # 16,2 -> 1,32
  File "SHGD/feature_extract/extractor.py", line 149, in <module>
    extract_PANDA_skeleton_features()

**Comment by Jiaoma** [comment]
Hi, thank you for pointing out the mistakes in my code again. The modified part of the Unipose project is uploaded to this project at https://github.com/Jiaoma/SHGD/commit/7ba4f859b3c7d8095921e5098b5acf1e9dc92fb0. To run the skeleton feature extraction and see the visualization of extracted skeleton points, you need to first install visdom by `pip install visdom`, run `python -m visdom.server`, and then `cd feature_extract`, `python feature_extract/extractor.py`. The visualization results are shown at `http://localhost:8097/`.

**Comment by Mylszd** [comment]
Thanks for your reply！
